spring:
  datasource:
    url: jdbc:h2:mem:nydb
    username: user
    password:
    driverClassName: org.h2.Driver
    generate-unique-name: false
    name: parts
  h2:
    console:
      enabled: true